name: DevOps Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # AWS
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      # Frontend
      FRONTEND_ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME1 }}
      FRONTEND_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME1 }}

      # Backend
      BACKEND_ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME2 }}
      BACKEND_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME2 }}

      # SonarQube
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Tools
      SCANNER_HOME: /usr/local/sonar-scanner

    steps:
      # 1️⃣ Check Docker
      - name: Check Docker Version
        run: docker --version

      - name: Docker Info
        run: docker info

      # 2️⃣ Clean + Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4️⃣ SonarQube Scan - Frontend
      - name: SonarQube Scan Frontend
        working-directory: Application-Code/frontend
        run: |
          npm install
          npx sonar-scanner \
            -Dsonar.projectName=frontend \
            -Dsonar.projectKey=frontend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 5️⃣ SonarQube Scan - Backend
      - name: SonarQube Scan Backend
        working-directory: Application-Code/backend
        run: |
          npm install
          npx sonar-scanner \
            -Dsonar.projectName=backend \
            -Dsonar.projectKey=backend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # 6️⃣ Quality Gate - Frontend
      - name: SonarQube Quality Gate Frontend
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: Application-Code/frontend/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 7️⃣ Trivy File Scan
      - name: Trivy FS Scan Frontend
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'Application-Code/frontend'
          output: 'trivy-frontend.txt'

      - name: Trivy FS Scan Backend
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: 'fs'
          scan-ref: 'Application-Code/backend'
          output: 'trivy-backend.txt'

      # 8️⃣ Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_DEFAULT_REGION }}

      # 9️⃣ Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 🔟 Build + Push Frontend
      - name: Build & Push Frontend Docker Image
        working-directory: Application-Code/frontend
        run: |
          docker build -t $FRONTEND_ECR_REPO_NAME .
          docker tag $FRONTEND_ECR_REPO_NAME $FRONTEND_REPOSITORY_URI:${{ github.run_number }}
          docker push $FRONTEND_REPOSITORY_URI:${{ github.run_number }}

      # 1️⃣1️⃣ Build + Push Backend
      - name: Build & Push Backend Docker Image
        working-directory: Application-Code/backend
        run: |
          docker build -t $BACKEND_ECR_REPO_NAME .
          docker tag $BACKEND_ECR_REPO_NAME $BACKEND_REPOSITORY_URI:${{ github.run_number }}
          docker push $BACKEND_REPOSITORY_URI:${{ github.run_number }}

      # 1️⃣2️⃣ Trivy Image Scan
      - name: Trivy Image Scan Frontend
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: $FRONTEND_REPOSITORY_URI:${{ github.run_number }}
          output: 'trivy-frontend-image.txt'

      - name: Trivy Image Scan Backend
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: $BACKEND_REPOSITORY_URI:${{ github.run_number }}
          output: 'trivy-backend-image.txt'

      # 1️⃣3️⃣ Update Deployment YAML
      - name: Update Deployment File Frontend
        run: |
          git config user.email "mahmoudmuhammed23496@gmail.com"
          git config user.name "Mahmoud123759"
          cd Kubernetes-Manifests-file/Frontend
          IMAGE_TAG=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
          sed -i "s/$FRONTEND_ECR_REPO_NAME:$IMAGE_TAG/$FRONTEND_ECR_REPO_NAME:${{ github.run_number }}/" deployment.yaml
          git add deployment.yaml
          git commit -m "Update frontend image to version ${{ github.run_number }}"
          git push

      - name: Update Deployment File Backend
        run: |
          git config user.email "mahmoudmuhammed23496@gmail.com"
          git config user.name "Mahmoud123759"
          cd Kubernetes-Manifests-file/Backend
          IMAGE_TAG=$(grep -oP '(?<=backend:)[^ ]+' deployment.yaml)
          sed -i "s/$BACKEND_ECR_REPO_NAME:$IMAGE_TAG/$BACKEND_ECR_REPO_NAME:${{ github.run_number }}/" deployment.yaml
          git add deployment.yaml
          git commit -m "Update backend image to version ${{ github.run_number }}"
          git push